server {
    listen 80;
    server_name localhost;

    # Serve AI context markdown files directly from Nginx as static files.
    location = /guard_rails.md {
        root /usr/share/nginx/html;
        default_type text/plain;
    }

    location = /skills.md {
        root /usr/share/nginx/html;
        default_type text/plain;
    }

    location = /context.md {
    root /usr/share/nginx/html;
    default_type text/plain;
    }

    location = /api_documentation.md {
    root /usr/share/nginx/html;
    default_type text/plain;
    }

    location = /available_api.md {
        root /usr/share/nginx/html;
        default_type text/plain;
    }

    # Forward all API routes to the Flask app container.
    location / {
        proxy_pass http://flask-api:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
